# Generated by Django 6.0.6 on 2026-07-01 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('preco_compra', models.FloatField()),
                ('preco_venda', models.FloatField()),
                ('cor', models.CharField(choices=[('azul', 'Azul'), ('vermelho', 'Vermelho'), ('verde', 'Verde'), ('amarelo', 'Amarelo'), ('branco', 'Branco'), ('preto', 'Preto'), ('marrom', 'Marrom')], max_length=20)),
                ('data_fabricacao', models.DateField()),
                ('imagem', models.CharField(help_text='Nome da imagem do produto', max_length=25)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.fabricante')),
            ],
        ),
    ]
